# Generated by Django 4.0.4 on 2022-05-10 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_come', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('quantity', models.SmallIntegerField()),
                ('supplier', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time_open', models.TimeField()),
                ('time_close', models.TimeField()),
                ('quantity', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('view', models.CharField(choices=[('p', 'Product'), ('w', 'Wear')], max_length=1)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.goods')),
            ],
        ),
    ]
